---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client-pvc
  resources:
    requests:
      storage: 15Gi
