---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: selfhosted-tandoor
  namespace: flux-system
spec:
  path: ./kubernetes/apps/selfhosted/tandoor/app
  targetNamespace: selfhosted
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  commonMetadata:
    labels:
      app.kubernetes.io/name: &appname tandoor
  prune: true
  interval: 30m
  dependsOn:
    - name: cloudnative-pg-cluster
    - name: external-secrets-stores
  postBuild:
    substitute:
      APP: *appname
