apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ELjDB1XyhC6XfdEhv9I2asf/QfxKBZoWkhk73at+BWmbefkR,iv:h5xdsk+3NkF8tUW9LUzNL+ZZxivVdrE24fNuYgzH0Sc=,tag:IhSF9TKoXlSWJBHuKePdhg==,type:str]
    credentials.json: ENC[AES256_GCM,data:3heXdounyOgbEhCur0cnonsOyKdYF+y8lNg15vKdP0tBr56PUcK2HDteS5ycYXks7tZG3Ri3ZkbZyceZGj3+djE72YwF6sYexrvwDjM+dvhFgLA9XCZfIrwRjmDjji0xl5RhY3/gcLEST7euSjIFOX8iHubImjf6vXzBztBLDuGpbW2883MeblBYwJojzfHY4djsub8lIQAF47rlfTRnAeYwNeX9GYlcWemb2rb+AQ==,iv:pdonH/tPopQzYrQefr7QG6/2Gv9zDxqUoTBy/KBdz0I=,tag:L6N8RoyUIq0hK10GbPfa8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ry3yxrdedaz6jy4f5qqy7ezge0tn2ch85saghxhcauyfu3ddygjsd7v3ts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbEJuZGpQZXgySFNpT1Yw
            QkVCZzRzQXJENzFqQ0YzOXZLQ2I3cTRJOTJvClFUbGdMQ3o4SHVXN0JKWGFFdXli
            dCt5SUNQd2JET01Tayt4VEtaNG02SWsKLS0tIDRha0pWcEswb0lLYUc0bFc5UnRr
            OUJ0ZTZTVzNQOGRuOUhZQ0pNKzZiSUEKMRaveNId/bFvc1r9LSqeqM7exALFjzkM
            zMnTGxSRKtdRuHVl/J/MovW7GiS5hNgILVJkW8Bo22UZsc119MN2lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-10T06:23:58Z"
    mac: ENC[AES256_GCM,data:6LXYlMiEfWfzSlfCyWLWYucStk2Jex1J8eu3fkgxW9Z6l6MkLaCyRZnv98gEbSQjjHMmD+sf/nTSbR1FnkxSzjc+1Zny7vr/kRSTtM0k1gerYL7ngyvJhBeZ3XsRjgMJ3GOhYNGvmSto9hKxgKdC+SIWcgcGm9lcgM9mTHa1N1w=,iv:7CgTw11PBB4/Ar0u+veUefmbtnvLs8E82yLeZOSTMWc=,tag:Skz+WEZeK7TrpJvE3GyMAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
