---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client-pvc
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.2.147
  share: /volume1/kubedata/PersistentVolumeClaims
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
