---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Communicate:
        - Discord:
            - icon: discord.png
              href: 'https://discord.com/app'
        - Gmail:
            - icon: gmail.png
              href: 'http://gmail.com'
        - Google Calendar:
            - icon: google-calendar.png
              href: 'https://calendar.google.com'
    - Media:
        - YouTube:
            - icon: youtube.png
              href: 'https://youtube.com/feed/subscriptions'
    - Reading:
        - Reddit:
            - icon: reddit.png
              href: 'https://reddit.com'
    - Git:
        - kubesearch:
            - icon: kubernetes-dashboard.png
              href: 'https://kubesearch.dev/'
        - k3s-home-cluster:
            - icon: github.png
              href: 'https://github.com/Deatrin/test-ops'
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Calendar:
    #     - Calendar:
    #         widget:
    #           type: calendar
    #           firstDayInWeek: sunday # optional - defaults to monday
    #           view: monthly # optional - possible values monthly, agenda
    #           maxEvents: 10 # optional - defaults to 10
    #           integrations: # optional
    #             - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
    #               service_group: Downloads # group name where widget exists
    #               service_name: Sonarr # service name for that widget
    #             - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
    #               service_group: Downloads # group name where widget exists
    #               service_name: Radarr # service name for that widget
    #             - type: readarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr, lidarr, readarr
    #               service_group: Downloads # group name where widget exists
    #               service_name: Readarr # service name for that
        # - Agenda:
        #     widget:
        #       type: calendar
        #       view: agenda # optional - possible values monthly, agenda
        #       maxEvents: 20 # optional - defaults to 10
        #       integrations: # optional
        #         - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
        #           service_group: Media # group name where widget exists
        #           service_name: Sonarr # service name for that widget
        #         - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
        #           service_group: Media # group name where widget exists
        #           service_name: Radarr # service name for that widget
        #         - type: readarr # active widget type that is currently enabled on homepage - possible values: radarr, sonar>
        #           service_group: Media # group name where widget exists
        #           service_name: Readarr # service name for that widget
    # - Media:
    #     - Tdarr:
    #         href: &url https://tdarr.${PI_DOMAIN}
    #         icon: tdarr.png
    #         description: Media Transcoding
    #         widget:
    #           type: tdarr
    #           url: *url
    - Infrastructure:
        - Cloudflared:
            href: https://dash.cloudflare.com/
            icon: cloudflare-zero-trust.png
            description: Cloudflared Tunnel Status
            widget:
              type: cloudflared
              accountid: {{HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID}}
              tunnelid: {{HOMEPAGE_VAR_CLOUDFLARED_TUNNELID}}
              key: {{HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN}}
        - Unifi:
            href: https://unifi.ui.com
            icon: unifi.png
            description: Unifi Dashboard
            widget:
              type: unifi
              url: https://192.168.1.1:443
              username: {{HOMEPAGE_VAR_UNIFI_USERNAME}}
              password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}
        # - NextDNS:
        #     href: https://my.nextdns.io
        #     icon: nextdns.png
        #     description: NextDNS
        #     widget:
        #       type: nextdns
        #       profile: {{HOMEPAGE_VAR_NEXTDNS_ID}}
        #       key: {{HOMEPAGE_VAR_NEXTDNS_API}}
        # - Portainer:
        #     href: &url https://portainer.${PI_DOMAIN}
        #     icon: portainer.png
        #     description: Docker Container Management
        #     widget:
        #       type: portainer
        #       url: *url
        #       env: 1
        #       key: {{HOMEPAGE_VAR_PORTAINER_TOKEN}}
    # - Selfhosted:
    #     - placeholder:

    # - Storage:
    #     - Unraid:
    #         href: https://nas.${PI_DOMAIN}
    #         icon: unraid.png
    #         description: Unraid NAS
  settings.yaml: |
    title: Dashboard
    favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/heimdall.png
    theme: dark
    background:
      image: https://images.unsplash.com/photo-1542396601-dca920ea2807?q=80&w=3451&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
      opacity: 50
    color: slate
    headerStyle: clean
    layout:
      Calendar:
        style: column
        icon: mdi-calendar
      Media:
        style: column
        icon: mdi-play-circle
      Infrastructure:
        style: row
        columns: 3
        icon: mdi-server
      # Storage:
      #   style: row
      #   columns: 2
      #   icon: mdi-desktop-tower
      Home:
        style: column
        icon: mdi-home-analytics
      # Observability:
      #   style: column
      #   icon: mdi-chart-line
      # Minecraft:
      #   style: row
      #   columns: 3
      #   icon: mdi-minecraft
      Selfhosted:
        style: row
        columns: 3
        icon: selfhosted.png
      Downloads:
        style: row
        columns: 3
        icon: mdi-download-circle
    # providers:
    #   longhorn:
    #     url: http://longhorn-frontend.storage
  widgets.yaml: |
    # - resources:
    #     backend: kubernetes
    #     cpu: true
    #     expanded: true
    #     memory: true
    - logo:
        icon: https://raw.githubusercontent.com/LilDrunkenSmurf/k3s-home-cluster/main/icons/lds-transparent.png
    - search:
        provider: [duckduckgo, google]
        focus: false
        target: _blank
    - greeting:
        text_size: xl
        text: "Howdy Hey!"
    # - kubernetes:
    #     cluster:
    #       cpu: true
    #       label: cluster
    #       memory: true
    #       show: true
    #       showLabel: true
    #     nodes:
    #       cpu: true
    #       memory: true
    #       show: false
    #       showLabel: true
    - openmeteo:
        label: Home
        # latitude: ${HOMEPAGE_VAR_LATITUDE}
        # longitude: ${HOMEPAGE_VAR_LONGITUDE}
        units: imperial
        cache: 5
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
