---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name tandoor-secret
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Tandoor
        POSTGRES_HOST: &dbhost postgres-rw.database.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_DB: &dbname "{{ .POSTGRES_DB }}"
        POSTGRES_USER: &dbuser "{{ .POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbpass "{{ .POSTGRES_PASS }}"
        SECRET_KEY: "{{ .SECRET_KEY }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: tandoor
    - extract:
        key: cloudnative-pg
