---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-data
  namespace: selfhosted
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client-pvc
  resources:
    requests:
      storage: 15Gi
