apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:M/TqMwWC3pPq9d5wJ1o=,iv:Ns5ns18TTRyYXFQigsdek7u1hk2JYvZKKjROqqgyDds=,tag:wNaZvj4+8YWRrZP729+Jhg==,type:str]
    username: ENC[AES256_GCM,data:U7RFY6cNkQ==,iv:iHowEAfPUT3aH4PSlfunFRWRznsbMocKMggK+F+iQcA=,tag:hZEXYlobfYBjc1u/D5g4vg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ry3yxrdedaz6jy4f5qqy7ezge0tn2ch85saghxhcauyfu3ddygjsd7v3ts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBna2dFMUowMGkra3QybzUr
            N1o1UW5xeUo0VE5CbTJOVXFkRGdEdCtYQms4CllsRWRHd2tTUkRXcTdBME9Nd2g2
            RnFvZXlXemp6Tld1aDF5T3Y3aWduazQKLS0tIDhCVkdYT25aeG1XRVhCekpWNjd2
            b3hxZ0p6elhqVnRjSHJuTmlIbm4zTFUKdjMXv1mcdip2lVIcr/ZXQuvnW4PH5uNK
            5oH0plKPCK+i58kdvESl7NSZoBx6bwpNtaCSSuTefO9dIoqL5oNzsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-10T07:19:55Z"
    mac: ENC[AES256_GCM,data:l0hsRizR57KMUNbdv19CYDLe45FoNwt43g7wziXdtZ5AygIseA8uSlAGrfxSzImcdLmAKboQ3KjFQIOZw8DhTECp41GfwVdbeilVwGwCA3UTvQEBipF9uT/yG/FdM/1iyvcU0oLBqMdUxPOf0NvxUdIV6zKEhfyWjXCb9qZMkCg=,iv:e/TiOo/bw5aPS77oES8YvknWJAzbgEUD/s/Ihw70GuI=,tag:wKPr3IXAGBRrpAOc1Z8bUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
