apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:5eRPndIGZSaRcOFiASKVZXx797CTyBJnhkcDNN/SVXIeC23OlU9BFIgGiCCj6Xl221nNTD5jaw8WKJSFJxucXQsbuhqsGuEgUrcKfuofJsTB/Fiy1utpYrBlUCI+EQ==,iv:kIa94YDw6UXWGcOKsNO8feIqcNppNd6F5qVozqXcQzI=,tag:bKgMyAlV9Wt+l9eZ7z5cGg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:XAC6Wx0KeiAL,iv:3IyqJRWi8jvPFMvfiVzTRhaEGS3e3SnMoyoan9wXTLw=,tag:02fVHcrgRB+DvjvSoVj76w==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:UqT/Zg2KSngGTy2sJ6wIVXo=,iv:97LZuymLJz/OwjBXqssOzJLSssEHhXLYII3UORdSQHE=,tag:2dloHtzSYsKJb+Tufi8eBw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:vtRfg7XgSRSgJ4Ze8tAvxpOJ29o7reqXTONj5UK6svw1DckO,iv:g5LtDye+FZPJs6PmNVb+x88lbk1egZo3Ls+ItMQGEgM=,tag:/mG/Yq2wf3IGLsAA1dL01A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ry3yxrdedaz6jy4f5qqy7ezge0tn2ch85saghxhcauyfu3ddygjsd7v3ts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxaUkzUGx1czlnRWF3QVB6
            YWNNQmEzUkY1ZEtZc0ljRjFJdnU1UnNLaVFzClRwNjZGd1NkMkVQaW1VenAyVnhq
            Z3U4dStxL1hQMHZhK01mNEtKR3Z1MHMKLS0tIDBPTlRXS2xWeEZ6c3N4U3RhN0Zj
            Tk81WmlRZTBZTnZBcW5zNjhLcVRkMGsKXzcI9GWLlk3wuqLd7+Hz6lfpW6GWpcRf
            DnBsOhKuoy3q0Y+wpvvPLFxY54gwoqH28N8j1cW0Ng2ADnNcRLzmgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-10T06:23:58Z"
    mac: ENC[AES256_GCM,data:7lJnfPql/5xj7ySst9KmrLnKMt4uZjpU5C2xzqKrKP/UxEzfzarVrQ9dAl15bJ08OjWI5SGp4Bh182lru5JhbKQXZ5Rr0vBUycObWpA7f1I4erftUZsRwypkihyYcMBdwAUNTLwvaTBpcMb8rEqmCb5slZDpcR7dSUd9Ff9sWCY=,iv:HeXGG41uQ1IJZe8AI5Koy5KCULTi0DHQl6aKZfqnYxI=,tag:a3XovWbBLX0h5446n/qNQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
