apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:hmp5DB7gD2aj925489lhq796dJ03u2YNfkI0qR5BmqFFZJWgAKbytRzO50bafILLkLKGs+6MEENhtppVfl55R117cJyVk0cJQ1o5e1bGKh8o7KaF4HwPLOZsgQl8MQ==,iv:olmHZd1bQWKlx45oZZhJEc7irFHVP0GhsoBQ8FxhtVc=,tag:hV9M4zhhio5egei/LSjJdw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:yfQujVCzjtrI,iv:N6xa81dW5C0QLG2aN5Kox8tLHEoXLxVG932SFJUJXHQ=,tag:EDWZBw6oTxB68Wj+ACtI+g==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:rWuP8zc9ym/AzLpF+TDpoCw=,iv:M1/LRbGwhAMzRK7169Su3d90i80Ul4ykDWwkZ4QniNA=,tag:h9s5sypc4QRe8shG0kKo+w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Kb1iwF1N59nqa2iMigFXAL1eI7OVAo5Cv7YAyYxKj+5+6tk/,iv:CdMsDTKb1oOHqYt28/f9xFThknJlUMsHooKfph0Wjaw=,tag:0DNz45S+y87MI08PPxMk1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ry3yxrdedaz6jy4f5qqy7ezge0tn2ch85saghxhcauyfu3ddygjsd7v3ts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKb0NhVlp1SWlvdmVFZTgv
            b0R4WmhUY0taTWtvZzJiYkowNk9RQXFna3l3Cjh4TExzQzZNOG5INEhKOTcySE1y
            cmE1UUwycWx0RWZZd3crR2NGYk5PTkEKLS0tIFp1dnlLQ0VLc3NJSmJmVzhrbGhF
            MmMyV0RxZTJDMjlKVXZUQmQyVWRNTEkK1LyvLPlAnLpIeM0lOBR47jYpAZ/yAmGl
            wy7f5sIlK8WFNg8tD/K+jVCDchkKqK1LsmaM1Sch6OB5BjYw365lsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-10T06:22:22Z"
    mac: ENC[AES256_GCM,data:bEN4SC34ayrEo5urorn6P9xW55t83G5Ha0L6ReNzy5pl6PGkCKKbUxQWYxbV1yFPgMj4aScZEuDOx/wiIiYbphU/p3JbmObjhU/5Y5MJXItzb7kd2ewfE+YjBKahY44dxrOgyh3MNvYC34AlD6rMjVC+vCt4NGqDQ5LilXWVurc=,iv:4au0ktPnxf8MZ9I8disgxXblhiTQVc3lym8+e67ixMM=,tag:3C41A/f44Bk3HZlBA3XHoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
