apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:EZxxyozROFS/uZJNPVnkI6VI4eozi/gLrDaiEnzcIaCt8N5zyJB7XgECQXCJ98ZXzdd1ErC808JfVAFnwKMbDkkLpWwzEz5ceTGty4A7JaLo4k1Xi9pyhRID4+Typg==,iv:lTgDo93ora0fGPuR2U66H68UbmnjtaqJaz1EVpr3jQM=,tag:b/gAmQ8Wrw0lRlz+2e5dFA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:NSlE5M6YOOuf,iv:ASDBc+kDI9wV0ZZuTy3HgK6IZ8fcdlkr+rgVR1XLG5Y=,tag:KsHBe9jjeVanv/3VGqHOTg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:O3YIi4ezPSHAsQlMX4FlhwI=,iv:FNnYAkJ914yQM7gnXnV2S+vgfehMBvtsrNoUzqsNMgM=,tag:4BZxfm1CfRWSLEQx6I6NAA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:R5EXjnAEN0kALssCD1u5HbauhKJyBB8K91z83maEK5eL8KU5,iv:if2fuU88aHjVykpRn564zxfiw5CpI9xTDMEDTwUbbHY=,tag:za9pAZhlnhGTLl85jPfW8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ry3yxrdedaz6jy4f5qqy7ezge0tn2ch85saghxhcauyfu3ddygjsd7v3ts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUS0l3aExwSGgwN2taTmxx
            NXN1dktCbTIrOGx4Snl4Vy9HYjFoVlYrdnc4CktTejVvQTVmWVpaSUlZVWFuL1hh
            RWFoMGdBci91MlpQemN0R0pQbTFoaEUKLS0tIDd6ckkwdm1XcjJSZmp6bWJnYlNQ
            dFJqdUJ2eG5SSE1pYm1qdDR5cGNqUW8KaC8ezcQAeDT4Gc87ck0l6WK2zqS1fS41
            Goa3FuESratPkYt1bsVQPYwacpq18Y+AbTYkXgsELjGszrPvHSCYgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-10T07:37:23Z"
    mac: ENC[AES256_GCM,data:pENnefTz9My7zmdtOQHwGc0RPMGoXpGNc2z9wMBECV+XNIdo38VVFXo1q2WT4TgmT5QF+dliXD7SyPkPh/vqNaXhjsfc9ly1yYBIkkTtPvVVdWHdMDlu0Rt1Fr7JqHvq5NE4XZWj9YKcbjs72UUKewlkQrdQ4SW6/ZKAtOEGPrc=,iv:Rmgjaf6kcET0tw6lfsTUjmX5hcM0Q2SdiZygNLnX24M=,tag:syRzIhpgvtEc/ImJoWPh4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
