apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:ZzVOgFScu43Y6Mykmmf+AZo17onr4hF3VpltZGW2jXKf7bC0rY2r5Q==,iv:+n2Aib7rr1PNcbkNtbIkbmb0MsrC54R75D/SX40hYeA=,tag:P+GC+gv7azzi6QB3r2wEIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ry3yxrdedaz6jy4f5qqy7ezge0tn2ch85saghxhcauyfu3ddygjsd7v3ts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrS0NuelpISEgySWU1LzFi
            ZnhudXdNQjBPTGVuMmxpZEdhMURja3g4cnhRCnIrTmZHUVoxNytlNXZia212SGdP
            T2tiZEN2L0Zpckx1VWRMQ0tLQmR4WnMKLS0tIEVPT3V6QmVXVzY3MWJjelR4Rlk0
            cDdOQktrOHllWXVmQVFBaGRUT2wyT0UKPWcTuKHAjDBUSMDurbkBY+lGSfkw7Tht
            OKzQL9fKImUBckosbApfIIUVS446I3QtDqEWtU4DANFKdJ4d2tZwKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-10T06:22:22Z"
    mac: ENC[AES256_GCM,data:7aPfvBthd0z33eMDyRXsBaYrlwFCpcwbx52K446QMXFxyfzIHAlDsSQK71UIRLN+i9U95vor72h8Hoa9+1fojAqfBp7JF8VHg+EiZKv9WRWasTHS7haza53RyDgMc9Br8/vDhGLwg0f6Xj8TKUziWIkspsYAse+ei1AnDsAyMy0=,iv:dIpGLE0cGbzVVEiSWVF/EKqCCMfWLukZcsLHKdUp7YA=,tag:dvBK7Xxkxqj9Egh2oDx8Xg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
