apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:NfvdAqw3QUUxWXjJg+w1ULmK5UIlaKnD4IGkArL2ML5sIIhY9IjzMQ==,iv:/hqNlOHmnvi1UF7DvMxJTWpAnHCCTzGKyC/LnOJdEDI=,tag:2bsOpO2ZQ39DPpGh94vvEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ry3yxrdedaz6jy4f5qqy7ezge0tn2ch85saghxhcauyfu3ddygjsd7v3ts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Yks0UzcwL3dZdWljVzg1
            UTRsYlg2WHpRK1B5SGY4Rm15dHVZR0NTZ3prCmt3RzFYT3ZVZ1BYMXM0YWxFNmp5
            N0dGSExjY3MxbGVvZWRSaVdKd0dFR0kKLS0tIHQ5aW1sclNIWHEvZEV6YzdmSmc3
            SVVKRnA5Zy8yR2VCalJTRld4aFhsUGMKZVIgIHR8KvEDa560K/XjrYZ0zSmwpiPH
            bWuPhEGEOnMeI4qog+lxSd9C1IX7MVDkG0VBCD/Yc10MHbFNopaOhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-10T06:55:08Z"
    mac: ENC[AES256_GCM,data:EhyUdAUDGpz3fGh5PBgRUDTpbiGezAuSzLwh+MrD1eu9Nf2VSbPmQsmBFhGxl8/BsTBRWTSfXik452SQR6NXEb84IWiIp4Xb12GQj0a+xHAEQYJ5Q3H3xhDb0P4h8Hj8xHhZTXgEbefUpXeIRpMSCHYH64WNVYNeWP9gtY4hYOY=,iv:0y+ITj1B6M4YQimhUijchI/JNrAkdtgpl97wpeANN4M=,tag:fZplwLbo3JtLRG3QhjjuQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
