apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:4kwDRDJbmRRkPJbAEe0KymP0ObfIseuam0FaJSu6qzpIlzjBPf3Wxg==,iv:IWg0NpXU1mOMpDZqD+Vx+nKjLJgQ7Ny7gd9PGWRV5BM=,tag:AAGNN6Amxi/TqFEl3ZdneQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ry3yxrdedaz6jy4f5qqy7ezge0tn2ch85saghxhcauyfu3ddygjsd7v3ts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVFVmT05Mem1UNkVNbjQz
            OE5OaVBVTXdDbUR1cTJ2eTA2dEFhbGZnMjNJClNMMFN5YnhPeTNLN291b3JXb3Ba
            MHdQK3U1TWJYc25HamdNb1JJSWtwdjgKLS0tIHo0dDRpMGUzZ1ZKdjNVbW5VUEFt
            Mmh4L0toRmhNV0JVTm1vWitKZXFaSEUK8BmT1soeQeoj5o33ltQsN1Xetu8qB71r
            ZvKijZEAMu4pJjosrWYg679JaMNZyT61VmIJ6OUoMicX1lQu6TZxUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-10T07:32:03Z"
    mac: ENC[AES256_GCM,data:/2HVqULnmX5s7Snee5u3sdYgCO0Tz6+OVQjHxw2ysmReltwgK3MJ/oKF4Pv8TQjj02aebMOF5kXnYbXdpVGyQtM6OttJrXGFZRZVM8Lq8TnKK5cBtsjwE0pvP8HjWgEON5sfSXSGnlvyzQ00CHsdmG6cvnUH/ne0grNDK/sZPM4=,iv:58zWLtc4EVyYO5x3Gbg0ZjbGBX9dJwRvWt+z4u6zNCQ=,tag:rJ+IX9D5KZlreTpiXxbXSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
